export default {
	color: 'primary',
	colors: null,
	density: 'default',
	drilldownKey: 'id',
	elevation: 1,
	expandOnClick: false,
	firstIcon: '$first',
	fixedFooter: true,
	fixedHeader: true,
	footers: [],
	headers: [],
	height: 'auto',
	hideDrilldownWhenLoading: true,
	hideNoData: false,
	hover: false,
	itemChildrenKey: 'child',
	// itemProps: ['foo'],
	// itemTitle: 'title',
	itemValue: 'id',
	items: [],
	itemsLength: 0,
	itemsPerPage: 5,
	itemsPerPageOptions: [
		{
			title: '5',
			value: 5,
		},
		{
			title: '10',
			value: 10,
		},
		{
			title: '25',
			value: 25,
		},
		{
			title: '50',
			value: 50,
		},
		{
			title: '100',
			value: 100,
		},
		{
			title: '$vuetify.dataFooter.itemsPerPageAll',
			value: -1,
		}
	],
	itemsPerPageText: '$vuetify.dataFooter.itemsPerPageText',
	lastIcon: '$last',
	lastPageLabel: '$vuetify.dataFooter.lastPage',
	level: 1,
	levels: 3,
	loaderHeight: '2px',
	loaderSize: 'default',
	loaderType: [
		'linear',
		// 'circular',
		// 'text',
		// 'skelton',
	],
	loading: false,
	loadingText: '$vuetify.dataIterator.loadingText',
	multiSort: false,
	mustSort: false,
	nextIcon: '$next',
	nextPageLabel: '$vuetify.dataFooter.nextPage',
	noDataText: '$vuetify.noDataText',
	// noFilter: false,
	page: 1,
	pageText: '$vuetify.dataFooter.pageText',
	prevIcon: '$prev',
	prevPageLabel: '$vuetify.dataFooter.prevPage',
	returnObject: true,
	search: '',
	searchDebounce: 750,
	searchMaxWait: 1000,
	searchProps: {
		cols: {
			lg: 3,
			md: 6,
			sm: 12,
			xl: 3,
			xs: 12,
			xxl: 2,
		},
		density: 'compact',
		variant: 'underlined',
	},
	server: false,
	showCurrentPage: false,
	showDrilldownWhenLoading: true,
	showExpand: false,
	showFooterRow: false,
	showSearch: false,
	showSelect: false,
	skeltonType: 'heading@1',
	sortBy: [],
	// sticky: false,
	// tag: 'div',
	// theme: undefined,
	// width: undefined,
};
